In [1]:
Y_clone = clone(X)
Y_clone == Y

NameError: name 'clone' is not defined

In [2]:
from mxnet import np, npx
from mxnet.gluon import nn

In [3]:
npx.set_np()

npx.cpu(), npx.gpu(), npx.gpu(1)

(cpu(0), gpu(0), gpu(1))

In [4]:
npx.num_gpus()

0

In [5]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    return npx.gpu(i) if npx.num_gpus() >= i + 1 else npx.cpu()

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu()]"""
    devices = [npx.gpu(i) for i in range(npx.num_gpus())]
    return devices if devices else [npx.cpu()]

try_gpu(), try_gpu(10), try_all_gpus()

(cpu(0), cpu(0), [cpu(0)])

In [6]:
#张量与GPU
# 默认情况下，张量是在CPU上创建的。
x = np.array([1, 2, 3])
x.ctx

cpu(0)

In [7]:
X = np.ones((2, 3), ctx=try_gpu())
X

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
Y = np.random.uniform(size=(2, 3), ctx=try_gpu(1))
Y

array([[0.5488135 , 0.5928446 , 0.71518934],
       [0.84426576, 0.60276335, 0.8579456 ]])

In [9]:
Y = np.random.uniform(size=(2, 3), ctx=try_gpu(1))
Y

array([[0.5448832, 0.8472517, 0.4236548],
       [0.6235637, 0.6458941, 0.3843817]])

In [11]:
Z = X.copyto(try_gpu(1))
print(X)
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
Y + Z

array([[1.5448833, 1.8472517, 1.4236548],
       [1.6235638, 1.645894 , 1.3843818]])

In [14]:
Z.as_in_ctx(try_gpu(1)) is Z

True

In [15]:
#神经网络与GPU
net = nn.Sequential()
net.add(nn.Dense(1))
net.initialize(ctx=try_gpu())

In [16]:
net(X)

array([[0.01776527],
       [0.01776527]])

In [17]:
net[0].weight.data().ctx

cpu(0)